# Generated by Django 4.2.4 on 2024-06-03 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_remove_user_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=8, null=True),
        ),
    ]
